### ISSUE TITLE
Read the feed of the heatcam.

### ISSUE THREAD

**Issue by Salt-Factory** [coaco-robot/coaco-robot#10]
**Describe the task**
The heatcam needs to be read.

**Depending on**
#4 

**Actions**
* Find the heatcam driver (ask Maarten Vandersteegen)
* Implement it

**Comment by DylanVanAssche** [comment]
Just follow the instructions here: https://github.com/maartenvds/libseek-thermal
Since we run our Docker with privileges, you can skip the UDEV rule thing.

**Comment by DylanVanAssche** [comment]
See https://github.com/coaco-robot/seek_compact_pro_node
