### ISSUE TITLE
Read heatcam feed of Turtlebot itself.

### ISSUE THREAD

**Issue by Salt-Factory** [coaco-robot/coaco-robot#18]
**Describe the task**
We were already able to read the heatcam off of a dummy setup; 
now we're ready for the real deal.

**Depending on**
#10 
#24 

**Actions**
Move the dummy setup over on the Turtlebot

**Comment by DylanVanAssche** [comment]
Works find using our ROS node, see https://github.com/coaco-robot/seek_compact_pro_node
We need the 3D printed case to test it on the Turtlebot (see #23 ).
